version: "3"
services:
  web:
    image: golang:1.12.6-stretch
    ports: 
      - 5000:5000
    environment:
     - "GO111MODULE=on"
    command:
      - "sh start.sh"
    labels:
      - "hey little mouse"
  # mysql:
  #   # replicas: 5
  #   image: mysql:5:7
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=capoomobi"
  #     - "MYSQL_DATABASE=capoomobi"
  #     - "MYSQL_USER=little_mouse"
  #     - "MYSQL_PASSWORD=big_cat"
  #   labels:
  #     - "little_mouse"
  #     - "little_cat"
  #   command: "sh ./help.sh"
  # front:
  #   image: node:12.4.0-stretch
  #   ports:
  #     - 8000:8000
  #   command:
  #     - "npm install"
  #     - "npm run build"
  #     - "npm run start"