version: "3"
services:
  web:
    image: golang:1.12.6-stretch
    ports:
      - 5000:5000
    environment:
     - "GO111MODULE=on"
    command:
      - "sh start.sh"
    labels:
      - "app=go"
      - "tier=api"
  mysql:
    # replicas: 5
    image: mysql:5:7
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=capoomobi"
      - "MYSQL_DATABASE=capoomobi"
      - "MYSQL_USER=little_mouse"
      - "MYSQL_PASSWORD=big_cat"
    labels:
      - "tier=database"
    command: "sh ./help.sh"
  front:
    image: gcr.io/hello-minikube-zero-install/hello-node
    ports:
      - 8080:8080
    labels:
      - "app=front"
  bobba:
    image: marci/bobbaorder:latest
    ports:
      - 8088:8088
    labels:
      - "app=bobba"
