image: "rust:1.40-stretch"

stages:
    - build
    - test
    - build_release

before_script:
    - apt-get update

install:
    stage: build
    script: cargo build

run test:
    stage: test
    script: cargo test

build release:
    stage: build_release
    script: cargo build --release
