image: "rust:1.41-stretch"

variables:
    RUST_BACKTRACE: 1

stages:
    - build
    - test
    - build_release

before_script:
    - apt-get update

install:
    stage: build
    script: cargo check

run test:
    stage: test
    before_script:
        - touch ~/.capoomobi.json
        - echo ${CAPOOMOBI} >> ~/.capoomobi.json
    script: cargo test -- --nocapture

run lint:
    stage: test
    before_script:
        - rustup component add clippy
    script: cargo clippy

build release:
    stage: build_release
    script: cargo build --release
    artifacts:
        paths:
        - capoomobi
        expired_in: 1 week
