image: "rust:1.41-stretch"

variables:
    RUST_BACKTRACE: 1

stages:
    - build
    - test
    - build_release

before_script:
    - apt-get update

install:
    stage: build
    script: cargo check

run test:
    stage: test
    before_script:
        - touch ~/.capoomobi.json
        - echo ${CAPOOMOBI} >> ~/.capoomobi.json
    script: cargo test -- --nocapture

run lint:
    stage: test
    before_script:
        - rustup component add clippy
    script: cargo clippy

run coverage:
    before_script: 
        - cargo install cargo-tarpaulin -f
    script:
        - cargo tarpaulin -v
    coverage: '/\d+.\d+% coverage, \d+\/\d+ lines covered/'

build release:
    stage: build_release
    script: cargo build --release
