[package]
name = "capoomobi"
version = "0.1.0"
authors = ["Yellowman <marc.inthaamnouay@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.0"
serde = { version = "1.0.91", features = ["derive"] }
