[package]
name = "capoomobi"
version = "0.1.0"
authors = ["Yellowman <marc.inthaamnouay@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.1"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
serde_yaml = "0.8.9"
colored = "1.8"
