apiVersion: apps/v1
kind: {{ ctrl }}
metadata:
  name: {{ name }}
  labels: {{ mapper labels 2 }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels: {{ mapper labels 4 }}
  template:
    metadata:
      labels: {{ mapper labels 6 }}
    spec:
      containers:
      - name: {{ name }}
        image: {{ image }}
        ports: {{ #each ports as |p| }}
          - containerPort: {{p}}{{ /each }}
        {{ #lengthie commands }}command: [{{ #each commands as |cmd| }}"{{ cmd }}"{{ /each }}]{{ /lengthie }}
