apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ name }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ ip }}
spec:
  rules:
    - http:
        paths: {{ #each backend as |b| }}
          - path: {{ b.path }}
            backend:
              serviceName: {{ b.service_name }}
              servicePort: {{ b.service_port }}{{ /each }}
