apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  labels: {{ mapper labels 2 }}
spec:
  type: {{ kind }}
  selector: {{ mapper labels 2 }}
  ports:
  - protocol: TCP
    port: {{ host_port }}
    targetPort: {{ target_port }}
    {{ #if nodeport }}nodePort: {{ nodeport }} {{ /if }}
